{
 "title": "Folding@Home",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "slot",
    "label": "Slot",
    "query": {
     "query": "fah_slot_status{instance=\"$instance\"}"
    }
   },
   { "name": "instance", "label": "Instance", "query": { "query": "fah_slot_status" } }
  ]
 },
 "panels": [
  { "title": "Slot #$slot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "slot" },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fah_slot_status{instance=\"$instance\", slot=\"$slot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Points per Day",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "k" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fah_queue_points_per_day{slot=\"$slot\", instance=\"$instance\"}/1000",
     "legendFormat": "{{instance}}, slot {{slot}}"
    }
   ]
  },
  {
   "title": "Current Work Unit progress",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fah_queue_percent_done{slot=\"$slot\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}, slot {{slot}}"
    }
   ]
  },
  {
   "title": "Work Unit running for",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-fah_simulation_start_timestamp{slot=\"$slot\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Unit ETA",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fah_simulation_eta_seconds{slot=\"$slot\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status over time",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fah_slot_status{slot=\"$slot\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Units",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fah_queue_state{slot=\"$slot\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}